export const themePalettes = { 
  dark: {
    name: "dark",
    background: "#121212",
    text: "#ffffff",
    primary: "#bb86fc",
    secondary: "#03dac6",
    subtitle: "#cccccc",
    cardBg: "#1c1c1c",
    titleColor: "#ffffff",
    sectionTitle: "#bb86fc",
  },
  light: {
    name: "light",
    background: "#f2f2f2",
    text: "#333333",
    primary: "#6200ee",
    secondary: "#03dac6",
    subtitle: "#666666",
    cardBg: "#e0e0e0",
    titleColor: "#333333",
    sectionTitle: "#6200ee",
  },
  blue: {
    name: "blue",
    background: "#0E1B2B",
    text: "#ffffff",
    primary: "#1E90FF",
    secondary: "#87CEFA",
    subtitle: "#cccccc",
    cardBg: "#1A2F48",
    titleColor: "#ffffff",
    sectionTitle: "#1E90FF",
  },
  pink: {
    name: "pink",
    background: "#FCE4EC",
    text: "#880E4F",
    primary: "#EC407A",
    secondary: "#F8BBD0",
    subtitle: "#BC477B",
    cardBg: "#F8BBD0",
    titleColor: "#AD1457",
    sectionTitle: "#EC407A",
  },
};